### ISSUE TITLE
how to run runtimesamp as an standalone application,not plugin?

### ISSUE THREAD

**Issue by zqudm** [sulir/runtimesamp#1]

**Comment by sulir** [comment]
RuntimeSamp is designed as a plugin. Since its purpose is to display sample values in the source code editor, it does not make sense to run it as a "standalone" application. Of course, support for multiple editors could be added. However, since this is only a proof-of-concept implementation, it is not a priority - there are more serious problems which should be solved first (such as the updating of the values when the code changes, which is an open research problem).

If you want to run only the data collection part without a IDE, you can append the "-javaagent:..." parameter described in the README to the "java" command line parameters. But you will still need the IDE to display the values.
